[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"
[build.environment]
  NODE_VERSION = "12.20.0"
  YARN_VERSION = "1.19.1"
  YARN_FLAGS = "--no-ignore-optional"
# Specific branch context:
# Deploys from this branch will take these settings
# and override their current ones.
[context.branch-deploy]
  command = "GATSBY_ACTIVE_ENV=development npm run build"
