backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: hgkhanh/cherie # Repo for pushing new commits. Make sure to replace with your repo!


media_folder: content/images
public_folder: images

collections:
  - name: product
    label: "Product"
    folder: "content/products"
    create: true
    identifier_field: name
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Details And Fit", name: "detailsAndFit", widget: "list" }
      - { label: "Feature Image", name: "featureImage", widget: "image" }
      - {
          label: "Gallery",
          name: "galleryImages",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
        }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Sizes", name: "sizes", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: post
    label: "Post"
    folder: "content/posts"
    create: true
    fields:
      - { label: Title, name: title }
      - { label: Date, name: date, widget: date }
      - { label: Cover, name: cover, widget: image }
      - { label: Body, name: body, widget: markdown }
    
